
server:
  port: 8080
spring:
  application:
    name: warehouse-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 172.32.2.158:80
        namespace: public
dubbo:
  application:
    name: warehouse-dubbo
  registry:
    address: nacos://172.32.2.158:80
  protocol:
    port: 20880
    name: dubbo
  scan:
    base-packages: com.xes.online.warehouse.dubbo
